name: ci-delete

on:
  delete: {}

jobs:
  delete-subdomain:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudflare
 
      - name: Delete subdomain
        run: |
          python pipeline/delete_subdomain.py
        env:
          DNS_TOKEN: ${{ secrets.DNS_TOKEN }}
          DNS_DOMAIN: domesday.fr
          DNS_SUBDOMAIN: ${{ env.GITHUB_REF_SLUG }}.esiee-hub
   
  undeploy:
    needs: delete-subdomain
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      - name: SSH and Docker Compose Down remove files
        uses: appleboy/ssh-action@v1.0.0
        with:
          envs : ESIEE_HUB_SERVICE
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }} 
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            cd /home/share/autodeploy
            ESIEE_HUB_SERVICE=${{ env.GITHUB_REF_SLUG }}
            FOLDER=branch.$ESIEE_HUB_SERVICE.esiee-hub.domesday.fr
            cd $FOLDER
            docker-compose down
            docker rmi domesday/esiee-hub:$ESIEE_HUB_SERVICE
            cd ..
            rm -rf $FOLDER
            rm /home/share/nginx_reverse_proxy/conf/conf_site/$ESIEE_HUB_SERVICE.esiee-hub.domesday.fr.conf
            cd /home/share/nginx_reverse_proxy/
            docker-compose restart
