name: ci

on:
  push: {}

jobs:
  subdomain:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ovh
 
      - name: Create subdomain
        run: |
          python pipeline/create_subdomain.py
        env:
          OVH_ENDPOINT: ${{ secrets.DNS_OVH_ENDPOINT }}
          OVH_APP_KEY: ${{ secrets.DNS_OVH_APPLICATION_KEY }}
          OVH_APP_SECRET: ${{ secrets.DNS_OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.DNS_OVH_CONSUMER_KEY }}
          OVH_DOMAIN: domesday.fr
          OVH_SUBDOMAIN: ${{ env.GITHUB_REF_SLUG }}.esiee-hub
  build:
    needs: subdomain
    runs-on: ubuntu-20.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
       
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/esiee-hub:${{ env.GITHUB_REF_SLUG }}
          platforms: linux/arm64/v8
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      - name: SSH and Docker Pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          envs : ESIEE_HUB_SERVICE
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }} 
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            cd /home/share/autodeploy
            ESIEE_HUB_SERVICE=${{ env.GITHUB_REF_SLUG }}
            sed "s/{{ESIEE_HUB_SERVICE}}/$ESIEE_HUB_SERVICE/g" docker-compose-model.yml > branch.$ESIEE_HUB_SERVICE.esiee-hub.domesday.fr/docker-compose.yml
            python conf_file.py $ESIEE_HUB_SERVICE
            cd $ESIEE_HUB_SERVICE.esiee-hub.domesday.fr
            docker-compose pull
            docker-compose down
            docker-compose up -d
