name: ci

on:
  push: {}

jobs:
  subdomain:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ovh

      - name: Create subdomain
        run: |
          python create_subdomain.py
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          OVH_DOMAIN: ${{ secrets.OVH_DOMAIN }}
          OVH_SUBDOMAIN: ${{ env.GITHUB_REF_SLUG }}.esiee-hub
  build:
    needs: subdomain
    runs-on: ubuntu-20.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3 
       
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/esiee-hub:${{ env.GITHUB_REF_SLUG }}
      #     platforms: linux/arm64/v8
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Docker Pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          envs : ESIEE_HUB_SERVICE
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            sed -i 's/^ESIEE_HUB_SERVICE=.*/ESIEE_HUB_SERVICE=${{ env.GITHUB_REF_SLUG }}/' .env
            cd /home/share/autodeploy
            docker-compose pull
            docker-compose down
            docker-compose up -d
